### PR TITLE
feat (/pfcast): add support for intercepting /pfcast calls to autorank spells there too

### PR DESCRIPTION
**Pull request by dsidirop**
This should enable smooth integration with any pfui-based mouseover and macro/supermacro. For example:

```lua
  alt=IsAltKeyDown()
  
  if alt then
      CastSpellByName"Divine Favor"
  else
      SlashCmdList.PFCAST("Holy Light")
  end
```

### CODE REVIEW

**Comment by melbaa** [comment]
this is relatively pointless given that
`/pfcast SmartHealer:CastHeal("Heal")`
already works for both hover casting and click casting

Does your code do anything extra?

**Comment by melbaa** [comment]
or in pure lua code
`/run SlashCmdList.PFCAST('SmartHealer:CastHeal("Heal")')`

I guess your hook saves some typing. How confident are you in the targeting stuff? you sure it's needed? asking because pfcast itself sets the target

**Comment by dsidirop** [comment]
> this is relatively pointless given that `/pfcast SmartHealer:CastHeal("Heal")` already works for both hover casting and click casting
> 
> Does your code do anything extra?

The approach you've given does indeed work however it's next to impossible for average-joe players to figure it out let alone debug it if they miss out on a quote - in their eyes it looks egyptian hieroglyphics and it's the reason that most addons designed by technically minded people fail to be adopted by the masses.

Technically oriented people fail to design good products because they can't get in the shoes of the average end-user to see the world through his point of view.

This patch on the other hand makes integration with pfcast seamless:

```
/pfcast Holy Light     <- gets autoranked    that's all there is to     plain and simple
```

**This is what an average-joe user can understand and already uses**. By simply installing the addon this patch ensures that all pfcast calls get auto-ranked right out of the box.

This patch also respects explicit ranking for more advanced users:

```
/pfcast Holy Light(Rank 3)
```

And of course this will keep working - so the patch is backwards compatible:

```
/pfcast SmartHealer:CastHeal("Holy Light")
```

**Comment by melbaa** [comment]
wtf did I just read

**Comment by shikulja** [comment]
@dsidirop 

/pfcast Быстрое исцеление (Mouseover no target)
SmartHealer.lua:162: Usage: UnitHealthMax("unit")

**Comment by melbaa** [comment]
I can't reproduce an error on the english client. Also I don't have lazyspell installed if that matters.
```
/pfcast Flash Heal
/pfcast Flash Heal(Rank 1)
```
etc all work for me

**Comment by shikulja** [comment]
@dsidirop 
/pfcast Flash Heal 
Causes an error if you use a macro\command on an empty space, without a target
image

**Comment by melbaa** [comment]
Ok, to reproduce it you need to have autoSelfCast 0

eg /run SetCVar("autoSelfCast", 0)

**Comment by shikulja** [comment]
I think function getProperTargetBasedOnMouseOver() needs to be updated and add a condition 
elseif GetCVar("autoSelfCast") == "0" then
            unit = "mouseover" --???

**Comment by melbaa** [comment]
I think it's enough to add 
```
        if unitstr == nil then return end
```
after getProperTargetBasedOnMouseOver(), so the code looks like this
```
        local unitstr = getProperTargetBasedOnMouseOver()
        if unitstr == nil then return end
        rank = self:GetOptimalRank(msg, unitstr)
```

This way the /pfcast won't do anything if there's no target.

**Comment by shikulja** [comment]
Yes it works well. Now autoSelfCast 1 and autoSelfCast 0 work as expected

**Comment by melbaa** [comment]
alright, pushed the fix https://github.com/melbaa/SmartHealer/commit/3c550f8ee8e185ee223d1a1f5910847fe81e92f9

thanks for reporting/testing.

**Pull request merged**
